const fs = require('fs');

const extraClosed = [
    { q: "What is the primary function of the 'Pointwise' convolution in MobileNet architectures?", o: ["Spatial downsampling of the input.", "Cross-channel combination of features extracted by depthwise filters.", "Increasing the non-linearity of the model.", "Reducing the total number of input channels."], a: 1, e: "Pointwise convolutions (1x1) linearly combine the output of the depthwise layer across the channel dimension." },
    { q: "Which of the following best describes 'Structured Pruning'?", o: ["Removing individual weights randomly across the network.", "Removing entire channels, filters, or blocks to maintain dense matrix structures.", "Pruning only the fully connected layers.", "Setting weights to zero only if they are exactly zero."], a: 1, e: "Structured pruning removes organized groups of weights (like filters), which aligns better with hardware acceleration than unstructured sparsity." },
    { q: "In Post-Training Quantization (PTQ), why might asymmetric quantization be preferred over symmetric quantization?", o: ["It requires less memory for the scaling factor.", "It handles distributions with a non-zero mean more effectively without wasting representational range.", "It eliminates the need for a Zero-Point.", "It allows for 4-bit precision instead of 8-bit."], a: 1, e: "Asymmetric quantization uses a zero-point to shift the range, perfectly mapping unbalanced floating-point distributions to the full 8-bit range." },
    { q: "What is the primary limitation of 'On-device Learning' compared to Cloud Training?", o: ["Lack of data privacy.", "High latency for inference.", "Severely constrained SRAM and processing power for backpropagation.", "Inability to use convolutional layers."], a: 2, e: "Backpropagation requires storing intermediate activations and gradients, which rapidly exhausts the small SRAM on microcontrollers." },
    { q: "In the context of the ESP32-S3, what is 'Tiling' (or Patching)?", o: ["Dividing the source code into smaller modules.", "Processing a large input feature map in smaller spatial blocks to fit within SRAM limits.", "Distributing the workload across multiple microcontrollers.", "A form of data augmentation for training images."], a: 1, e: "Tiling involves computing the network on sub-regions of the input, managing peak memory at the cost of some re-computation at boundaries." },
    { q: "Which evaluation metric is critical when designing Early Exit architectures?", o: ["Training loss.", "The trade-off curve between average inference latency and classification accuracy.", "The number of epochs required for convergence.", "The physical size of the camera sensor."], a: 1, e: "Early exit models are evaluated by how much latency they save versus how much accuracy is sacrificed at different confidence thresholds." },
    { q: "What role does the 'Linear Bottleneck' play in MobileNetV2?", o: ["It prevents the destruction of information caused by non-linearities (like ReLU) in low-dimensional spaces.", "It reduces the spatial resolution of the image.", "It increases the number of channels before depthwise convolution.", "It applies dropout to prevent overfitting."], a: 0, e: "Using a linear activation at the bottleneck layer preserves the information that would otherwise be lost if a ReLU zeroed out negative values." },
    { q: "What is 'Knowledge Distillation' in the context of model compression?", o: ["Converting 32-bit floats to 8-bit integers.", "Training a smaller 'student' model to mimic the soft outputs of a larger 'teacher' model.", "Removing redundant filters based on L1-norm.", "Fusing multiple layers into a single computational kernel."], a: 1, e: "Distillation transfers the generalized knowledge (soft probabilities) from a complex model to a compact one suitable for the edge." },
    { q: "Why is 'Sample Partitioning' based on user ID important in wearable sensor datasets?", o: ["To balance the classes in the dataset.", "To prevent 'data leakage' where correlated samples from the same user appear in both train and test sets, artificially inflating accuracy.", "To reduce the overall size of the dataset.", "To speed up the training process."], a: 1, e: "Sensory data is highly correlated per user; partitioning by user ensures the model's ability to generalize to unseen users is accurately measured." },
    { q: "What does 'QAT' (Quantization-Aware Training) model during the forward pass?", o: ["The effect of pruning.", "The latency of the final device.", "The clipping and rounding errors introduced by INT8 inference.", "The battery consumption of the MCU."], a: 2, e: "QAT uses 'Fake Quantization' nodes during training to simulate quantization error, allowing the model weights to adapt to the loss of precision." },
    { q: "Which statement is true about 'Weight Sharing'?", o: ["It shares weights between the CPU and the cloud.", "It clusters weights into groups (e.g., using K-means) and represents them with a codebook, reducing storage.", "It copies the weights of the first layer to all subsequent layers.", "It shares weights between different users in federated learning."], a: 1, e: "Weight sharing replaces individual weights with an index to a shared codebook of centroids, drastically reducing Flash footprint." },
    { q: "In SqueezeNet, what is the ratio of squeeze filters to expand filters typically used?", o: ["The number of squeeze filters is strictly larger.", "The number of squeeze filters is less than the total number of expand filters (typically 1/8 to 1/4).", "They are exactly equal.", "It depends entirely on the input image size."], a: 1, e: "The squeeze ratio limits the number of channels entering the 3x3 expand filters, heavily reducing the parameter count." },
    { q: "What is the primary advantage of deploying a model on an MCU rather than sending data to the cloud?", o: ["Infinite compute capacity.", "Deterministic low latency, privacy preservation, and independence from network connectivity.", "Ability to train massive transformer models.", "Easier debugging in Python."], a: 1, e: "Edge AI guarantees response times, keeps sensitive data local, and works without an internet connection." },
    { q: "How is the 'Receptive Field' affected by increasing the stride of a convolution?", o: ["It decreases.", "It remains the same.", "It increases, allowing deeper layers to capture information from larger areas of the original input.", "It becomes zero."], a: 2, e: "Stride reduces spatial dimensions, effectively expanding the field of view of subsequent filters relative to the original image." },
    { q: "What is the main challenge of 'Unstructured Pruning' on generic hardware like the ESP32-S3?", o: ["It severely degrades accuracy.", "Sparse matrices require specialized hardware or complex indexing to achieve actual speedups, often making execution slower on standard CPUs.", "It increases the number of MACs.", "It cannot be applied to convolutional layers."], a: 1, e: "Without hardware support for sparsity, the overhead of skipping zeros (branching/indexing) can outweigh the computational savings." }
];

const extraOpen = [
    { q: "DERIVATION: Calculate the Scale (S) and Zero-Point (Z) for a symmetric INT8 quantization scheme given a weight tensor with Min=-3.5 and Max=3.5.", a: "1. Symmetric range is [-127, 127].\n2. S = Max(|Min|, |Max|) / 127 = 3.5 / 127 ≈ 0.02756.\n3. Zero-Point (Z) is strictly 0 for symmetric quantization.", pts: 5 },
    { q: "SYSTEM DESIGN: Discuss the architectural changes required to convert a standard ResNet block into an 'Inverted Residual' block (MobileNetV2). Mention the sequence of layers and channel dimensions.", a: "Standard ResNet uses a 'bottleneck' (reduce -> 3x3 conv -> expand). Inverted Residuals reverse this: 1. Expand channels (1x1 Conv) to a high dimension. 2. Apply Depthwise Conv (3x3) in the expanded space. 3. Project back to low dimensions with a linear 1x1 Conv (bottleneck) and apply the skip connection.", pts: 5 },
    { q: "THEORY: Explain the concept of 'Concept Drift' in the context of deployed edge AI sensors. How does On-device Learning address this?", a: "Concept drift occurs when the statistical properties of the target variable change over time (e.g., sensor wear, new environments). The model's accuracy degrades. On-device learning allows the model to continuously adapt to the new distribution locally, using newly acquired labels or self-supervised signals.", pts: 5 },
    { q: "EXERCISE: A neural network layer produces an activation map of 64x64x32. Calculate the SRAM required to store this tensor in Float32 vs INT8.", a: "1. Total elements: 64 * 64 * 32 = 131,072.\n2. Float32 footprint: 131,072 * 4 bytes = 524,288 Bytes (512 KB).\n3. INT8 footprint: 131,072 * 1 byte = 131,072 Bytes (128 KB).", pts: 5 },
    { q: "HARDWARE ANALYSIS: Explain the 'Memory Wall' problem in edge AI accelerators and how 'Kernel Fusion' mitigates it.", a: "The Memory Wall refers to the bottleneck where data transfer (SRAM to registers) takes more time and energy than the MAC computation itself. Kernel Fusion combines sequential operations (e.g., Conv, Add Bias, ReLU) into a single loop, keeping the intermediate accumulator in registers and avoiding costly SRAM write/read cycles.", pts: 5 },
    { q: "THEORY: Contrast 'Transfer Learning' with 'Knowledge Distillation' for creating edge-deployable models.", a: "Transfer learning takes a pre-trained feature extractor and fine-tunes the head for a new task; the model size usually remains the same. Knowledge distillation trains a smaller, structurally different 'student' model to mimic the outputs of a large 'teacher', resulting in a compressed model optimized for the edge.", pts: 5 },
    { q: "EXERCISE: Describe the mechanism of a 'Branching' Early Exit architecture. How are the intermediate classifiers trained?", a: "Branching adds auxiliary classifiers at intermediate depths. During training, a joint loss function is minimized: L_total = L_final + alpha * (L_aux1 + L_aux2). This forces early layers to learn discriminative features sooner. During inference, computation stops if an auxiliary classifier's confidence exceeds a set threshold.", pts: 5 },
    { q: "SYSTEM DESIGN: You are processing 1D time-series data (e.g., ECG) using Conv1D on an ESP32. Compare the computational complexity (MACs) of a standard Conv1D vs a Depthwise Separable Conv1D. Assume Input length L, Channels C, Kernel size K, Filters F.", a: "Standard Conv1D MACs = L * K * C * F.\nDepthwise MACs = L * K * C.\nPointwise MACs = L * 1 * C * F.\nDepthwise Separable Total MACs = L*C*(K + F).\nRatio: (K+F) / (K*F). For large F, it approaches 1/K reduction in computation.", pts: 5 },
    { q: "THEORY: What is the 'Fake Quantization' node in QAT? Describe its forward and backward pass behavior.", a: "Forward pass: Fake quantization simulates the rounding and clipping of INT8, passing the quantized-dequantized values to the next layer. Backward pass: Since rounding is non-differentiable (derivative is 0), it uses the 'Straight-Through Estimator' (STE), passing the gradient unchanged (derivative = 1) to update the underlying FP32 weights.", pts: 5 },
    { q: "HARDWARE ANALYSIS: Discuss the specific challenges of implementing 'Backpropagation' on a microcontroller like the ESP32-S3.", a: "1. Memory: Backprop requires storing all intermediate activations from the forward pass, which quickly exceeds SRAM. 2. Compute: Calculating gradients for weights and activations is highly MAC-intensive. 3. Precision: Gradients are often small and require FP32 or FP16; standard INT8 accumulators easily underflow.", pts: 5 }
];

let content = fs.readFileSync('F:/Wiki/POLIMI/Embedded and Edge AI/Simulator/questions.js', 'utf8');

// Use regex or string manipulation to append carefully without destroying
content = content.replace('];\\s*const openPool', ',\n' + extraClosed.map(q => JSON.stringify(q, null, 4)).join(',\n') + '\n];\n\nconst openPool');
content = content.replace(/\];\s*$/, ',\n' + extraOpen.map(q => JSON.stringify(q, null, 4)).join(',\n') + '\n];');

fs.writeFileSync('F:/Wiki/POLIMI/Embedded and Edge AI/Simulator/questions.js', content);
